database:
  image: mysql
  container_name: database.dev
  command: mysqld --user=root --verbose
  volumes:
    - ./activiti-sql/mysql.create.engine.sql:/docker-entrypoint-initdb.d/mysql.create.engine.sql
    - ./activiti-sql/mysql.create.history.sql:/docker-entrypoint-initdb.d/mysql.create.history.sql
    - ./activiti-sql/mysql.create.identity.sql:/docker-entrypoint-initdb.d/mysql.create.identity.sql

  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "activiti"
    MYSQL_USER: "test"
    MYSQL_PASSWORD: "test"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
